[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "https://agenda-pro-2.netlify.app/*"
  to   = "https://www.agenda-pro-2.netlify.app/:splat"
  status = 301
  force = true
